[build-system]
# These are the assumed default build requirements from pip:
# https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support
requires = ['setuptools>=61.0', 'wheel']
build-backend = 'setuptools.build_meta'

[project]
name = 'climate_indices'
version = '1.0.13'
description = 'Reference implementations of various climate indices typically used for drought monitoring'
readme = 'README.md'
requires-python = '>=3.7, <3.11'
classifiers = [
     'Development Status :: 5 - Production/Stable',
     'Intended Audience :: Developers',
     'Intended Audience :: Education',
     'Intended Audience :: Science/Research',
     'License :: OSI Approved :: BSD License',
     'Programming Language :: Python :: 3.7',
     'Programming Language :: Python :: 3.8',
     'Programming Language :: Python :: 3.9',
     'Programming Language :: Python :: 3.10',
     'Topic :: Software Development :: Libraries :: Python Modules',
     'Topic :: Scientific/Engineering :: Atmospheric Science',
     'Topic :: Scientific/Engineering :: Physics'
]
dependencies = [
    'dask',
    'numba',
    'scipy',
    'xarray',
]

[project.optional-dependencies]
dev = ['build', 'pytest', 'tox',]

[tool.distutils.bdist_wheel]
universal = true

[project.scripts]
process_climate_indices = 'climate_indices.__main__:main'
spi = 'climate_indices.__spi__:main'

[project.urls]
'Homepage' = 'https://github.com/monocongo/climate_indices'
'Bug Tracker' = 'https://github.com/monocongo/climate_indices/issues'
